---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om-az
inputs:
  - name: pcf-automation
  - name: pcf-products
run:
  path: pcf-automation/pcf-opsman/install-pcf/ci/scripts/azure/ra_multirg/create-opsman-azure.sh
