---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om
inputs:
  - name: pcf-automation
params:
  OPSMAN_HOST: {{OPSMAN_HOST}}
  OPSMAN_USER: {{OPSMAN_USER}}
  OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
          
run:
  path: pcf-automation/pcf-opsman/install-pcf/ci/scripts/config-opsman.sh
