---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om
inputs:
  - name: pcf-automation
run:
  path:  pcf-automation/pcf-opsman/install-pcf/ci/scripts/configure-apm.sh
