---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om
inputs:
  - name: pcf-automation
params:
  OPSMAN_HOST: replace-me
  OPSMAN_USER: replace-me
  OPSMAN_PASS: replace-me
          
run:
  path: pcf-automation/pcf-opsman/install-pcf/ci/scripts/config-opsman.sh
