---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om
inputs:
  - name: pcf-automation
  - name: tool-om
params:
  ERT_SSL_CERT:
  ERT_SSL_KEY:
  ERT_DOMAIN:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  AWS_TEMPLATE:
  S3_ENDPOINT:
  SYSLOG_HOST:

run:
  path: pcf-automation/ci/scripts/upgrade-ert.sh
