---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om-aws
inputs:
  - name: pcf-automation
  - name: pcf-datadog-tile-get
run:
  path: pcf-automation/pcf-opsman/install-pcf/ci/scripts/upload-datadog.sh
