---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amdock/pcfom
    tag: "1.0"
inputs:
  - name: pcf-automation
run:
  path: pcf-automation/upgrade-pcf/ci/scripts/stage-products.sh
