---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om
inputs:
  - name: pcf-automation
run:
  path: pcf-automation/upgrade-pcf/ci/scripts/stage-products.sh
