---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rsamban/pcf-om
inputs:
  - name: pcf
run:
  path:  pcf/pcf-automation/pcf-opsman/install-pcf/ci/scripts/common/configure-azure-sb.sh
