groups:
- name: all
  jobs:
  - 1.create-vSphere-opsman
  - 2.config-opsman
  - 3.config-director-vSphere
  - 4.upload-ert
  - 5.configure-ert-vSphere
  - 6.apply-changes
- name: 1.create-vSphere-opsman
  jobs:
  - 1.create-vSphere-opsman
- name: 2.config-opsman
  jobs:
  - 2.config-opsman
- name: 3.config-director-vSphere
  jobs:
  - 3.config-director-vSphere
- name: 4.upload-products
  jobs:
  - 4.upload-ert
- name: 5.configure-products
  jobs:
  - 5.configure-ert-vSphere
- name: 6.apply-changes
  jobs:
  - 6.apply-changes

resource_types:
- name: mypivnet
  type: docker-image
  source:
    repository: rsamban/pivnet
    tag: "1.0"
- name: myhttp
  type: docker-image
  source:
    repository: rsamban/http
    tag: "1.0"
- name: myscp
  type: docker-image
  source:
    repository: rsamban/scp
    tag: "1.0"

resources:
#- name: pcf-automation
#  type: git
#  source:
#    branch: master
#    uri: git@gitlab.com:rsamban/pcf-automation.git
#    private_key: {{GIT_PRIVATE_KEY}}
- name: pcf-automation
  type: myscp
  source:
    host: {{SCP_HOST}}
    username: {{SCP_USERNAME}}
    private_key: {{SCP_PRIVATE_KEY}}
    source_dir: pcf-automation
- name: pcf-products
  type: myhttp
  source:
    http_host: {{HTTP_HOST}}
#- name: pcf-products
#  type: myhttp
#  source:
#    iaas: {{IAAS}}
#    api_token: {{PIVNET_TOKEN}}



jobs:
- name: 1.create-vSphere-opsman
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
    - get: pcf-products
      params:
        product_slugs:
        - product_slug: ops-manager
        product_versions:
        - product_version: {{OPSMAN_VERSION}}
  - task: create-opsman
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/create-vSphere-opsman.yml
    params:
      IAAS: {{IAAS}}
      OPSMAN_VERSION: {{OPSMAN_VERSION}}
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      VCENTER_HOST: {{VCENTER_HOST}}
      VCENTER_USER: {{VCENTER_USER}}
      VCENTER_PASSWORD: {{VCENTER_PASSWORD}}
      DATACENTER_NAME: {{DATACENTER_NAME}}
      CLUSTER_NAME: {{CLUSTER_NAME}}
      HOST_NAME: {{HOST_NAME}}
      NETWORK_NAME: {{NETWORK_NAME}}
      DATA_STORE_NAME: {{DATA_STORE_NAME}}
      OPSMAN_IP: {{OPSMAN_IP}}
      OPSMAN_NETMASK: {{OPSMAN_NETMASK}}
      OPSMAN_GATEWAY: {{OPSMAN_GATEWAY}}
      OPSMAN_DNS: {{OPSMAN_DNS}}
      OPSMAN_NTP: {{OPSMAN_NTP}}
      OPSMAN_VM_PASS: {{OPSMAN_VM_PASS}}

- name: 2.config-opsman
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: config-opsman
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/config-opsman.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}


- name: 3.config-director-vSphere
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: config-director
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/config-director.yml
    params:
      IAAS: {{IAAS}}
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      VSPHERE_TEMPLATE_DIR: "vSphere"
      VCENTER_HOST: {{VCENTER_HOST}}
      VCENTER_USER: {{VCENTER_USER}}
      VCENTER_PASSWORD: {{VCENTER_PASSWORD}}
      DATACENTER_NAME: {{DATACENTER_NAME}}
      DATA_STORE_NAME: {{DATA_STORE_NAME}}
      DISK_TYPE: {{DISK_TYPE}}
      VM_FOLER: {{VM_FOLER}}
      TEMPLATE_FOLDER: {{TEMPLATE_FOLDER}}
      DISK_PATH_FOLDER: {{DISK_PATH_FOLDER}}
      NTP_SERVERS_STRING: ntp.lab.ecsteam.local
      RESURRECTOR_ENABLED: true
      POST_DEPLOY_ENABLED: false
      BOSH_RECREATE_ON_NEXT_DEPLOY: false
      RETRY_BOSH_DEPLOYS: false
      BLOBSTORE_TYPE: Internal
      DATABASE_TYPE: Internal
      # vSphere az and network
      AZ_COUNT: {{AZ_COUNT}}
      NETWORK_COUNT: {{NETWORK_COUNT}}
      SUBNET_COUNT: {{SUBNET_COUNT}}
      NETWORK_CONFIG_TEMPLATE: {{NETWORK_CONFIG_TEMPLATE}}
      AZ1: {{AZ1}}
      CLUSTER1: {{CLUSTER1}}
      RESOURCE_POOL1: {{RESOURCE_POOL1}}

      SINGLETON_AVAILABILITY_ZONE: {{SINGLETON_AVAILABILITY_ZONE}}
      SINGLETON_NETWORK: {{SINGLETON_NETWORK}}
      NETWORK1: {{NETWORK1}}
      NETWORK1_IS_SERVICE: {{NETWORK1_IS_SERVICE}}
      VSPHERE_NETWORK11: {{VSPHERE_NETWORK11}}
      NETWORK1_CIDR1: {{NETWORK1_CIDR1}}
      NETWORK1_RESERVED1: {{NETWORK1_RESERVED1}}
      NETWORK1_DNS1: {{NETWORK1_DNS1}}
      NETWORK1_GATEWAY1: {{NETWORK1_GATEWAY1}}
###########################
## Job - Upload ERT      ##
###########################
- name: 4.upload-ert
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-automation
    - get: pcf-products
      params:
        product_slugs:
        - product_slug: stemcells
        - product_slug: elastic-runtime
        product_versions:
        - product_version: {{ERT_STEMCELL_VERSION}}
        - product_version: {{ERT_VERSION}}
  - task: upload-stemcell
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/upload-stemcells.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
  - task: upload-ert
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/upload-ert.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

# configure ert
- name: 5.configure-ert-vSphere
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: configure-ert
    file:  pcf-automation/pcf-opsman/install-pcf/ci/tasks/configure-ert-vSphere.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AZ_COUNT: {{AZ_COUNT}}
      AZ1: {{AZ1}}
      ERT_SINGLETON_AZ: {{ERT_SINGLETON_AZ}}
      ERT_DOMAIN: {{ERT_DOMAIN}}
      ERT_NETWORK: {{ERT_NETWORK}}
      ERT_SSL_CERT: {{ERT_SSL_CERT}}
      ERT_TEMPLATE: {{ERT_TEMPLATE}}
      HA_PROXY_IPS: {{HA_PROXY_IPS}}
      MYSQL_MONITOR_EMAIL: {{MYSQL_MONITOR_EMAIL}}
            
###########################
## Job - Deploy ERT      ##
###########################
- name: 6.apply-changes
  serial: true
  plan:
  - aggregate:
    - get: pcf-automation
  - task: apply-changes
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/apply-changes.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

