groups:
- name: all
  jobs:
  - 1.create-vSphere-opsman
  - 2.config-opsman
  - 3.config-director-vSphere
  - 4.upload-ert
  - 4.3.upload-splunk
  - 4.4.upload-datadog
  - 5.configure-ert-vSphere
  - 5.3.configure-splunk
  - 5.4.configure-datadog
  - 6.apply-changes
- name: 1.create-vSphere-opsman
  jobs:
  - 1.create-vSphere-opsman
- name: 2.config-opsman
  jobs:
  - 2.config-opsman
- name: 3.config-director-vSphere
  jobs:
  - 3.config-director-vSphere
- name: 4.upload-products
  jobs:
  - 4.upload-ert
  - 4.3.upload-splunk
  - 4.4.upload-datadog
- name: 5.configure-products
  jobs:
  - 5.configure-ert-vSphere
  - 5.3.configure-splunk
  - 5.4.configure-datadog
- name: 6.apply-changes
  jobs:
  - 6.apply-changes

resource_types:
- name: mypivnet
  type: docker-image
  source:
    repository: rsamban/pivnet
    tag: "1.0"
- name: myhttp
  type: docker-image
  source:
    repository: rsamban/http
    tag: "1.0"

resources:
- name: pcf-automation
  type: git
  source:
    branch: master
    #uri: git@192.168.61.5:root/pcf-automation.git
    #uri: git@github.com:rsamban/pcf-automation.git
    uri: git@gitlab.com:rsamban/pcf-automation.git
    private_key: {{GIT_PRIVATE_KEY}}
- name: pcf-products
  type: mypivnet  
  source:
    iaas: {{IAAS}}
    api_token: {{PIVNET_TOKEN}}



jobs:
- name: 1.create-vSphere-opsman
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
    - get: pcf-products
      params:
        product_slugs:
        - product_slug: ops-manager
        product_versions:
        - product_version: {{OPSMAN_VERSION}}
  - task: create-opsman
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/create-vSphere-opsman.yml
    params:
      IAAS: {{IAAS}}
      OPSMAN_VERSION: {{OPSMAN_VERSION}}
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      VCENTER_HOST: {{VCENTER_HOST}}
      VCENTER_USER: {{VCENTER_USER}}
      VCENTER_PASSWORD: {{VCENTER_PASSWORD}}
      DATACENTER_NAME: {{DATACENTER_NAME}}
      CLUSTER_NAME: {{CLUSTER_NAME}}
      HOST_NAME: {{HOST_NAME}}
      NETWORK_NAME: {{NETWORK_NAME}}
      DATA_STORE_NAME: {{DATA_STORE_NAME}}
      OPSMAN_IP: {{OPSMAN_IP}}
      OPSMAN_NETMASK: {{OPSMAN_NETMASK}}
      OPSMAN_GATEWAY: {{OPSMAN_GATEWAY}}
      OPSMAN_DNS: {{OPSMAN_DNS}}
      OPSMAN_NTP: {{OPSMAN_NTP}}
      OPSMAN_VM_PASS: {{OPSMAN_VM_PASS}}

- name: 2.config-opsman
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: config-opsman
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/config-opsman.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}


- name: 3.config-director-vSphere
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: config-director
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/config-director.yml
    params:
      IAAS: {{IAAS}}
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      VSPHERE_TEMPLATE_DIR: "vSphere"
      VCENTER_HOST: {{VCENTER_HOST}}
      VCENTER_USER: {{VCENTER_USER}}
      VCENTER_PASSWORD: {{VCENTER_PASSWORD}}
      DATACENTER_NAME: {{DATACENTER_NAME}}
      DATA_STORE_NAME: {{DATA_STORE_NAME}}
      DISK_TYPE: {{DISK_TYPE}}
      VM_FOLER: {{VM_FOLER}}
      TEMPLATE_FOLDER: {{TEMPLATE_FOLDER}}
      DISK_PATH_FOLDER: {{DISK_PATH_FOLDER}}
      NTP_SERVERS_STRING: ntp.lab.ecsteam.local
      RESURRECTOR_ENABLED: true
      POST_DEPLOY_ENABLED: false
      BOSH_RECREATE_ON_NEXT_DEPLOY: false
      RETRY_BOSH_DEPLOYS: false
      BLOBSTORE_TYPE: Internal
      DATABASE_TYPE: Internal
      # vSphere az and network
      AZ_COUNT: {{AZ_COUNT}}
      NETWORK_COUNT: {{NETWORK_COUNT}}
      SUBNET_COUNT: {{SUBNET_COUNT}}
      NETWORK_CONFIG_TEMPLATE: {{NETWORK_CONFIG_TEMPLATE}}
      AZ1: {{AZ1}}
      CLUSTER1: {{CLUSTER1}}
      RESOURCE_POOL1: {{RESOURCE_POOL1}}
      AZ2: {{AZ2}}
      CLUSTER2: {{CLUSTER2}}
      RESOURCE_POOL2: {{RESOURCE_POOL2}}
      AZ3: {{AZ3}}
      CLUSTER3: {{CLUSTER3}}
      RESOURCE_POOL3: {{RESOURCE_POOL3}}
      SINGLETON_AVAILABILITY_ZONE: {{SINGLETON_AVAILABILITY_ZONE}}
      SINGLETON_NETWORK: {{SINGLETON_NETWORK}}
      NETWORK1: {{NETWORK1}}
      NETWORK1_IS_SERVICE: {{NETWORK1_IS_SERVICE}}
      VSPHERE_NETWORK11: {{VSPHERE_NETWORK11}}
      NETWORK1_CIDR1: {{NETWORK1_CIDR1}}
      NETWORK1_RESERVED1: {{NETWORK1_RESERVED1}}
      NETWORK1_DNS1: {{NETWORK1_DNS1}}
      NETWORK1_GATEWAY1: {{NETWORK1_GATEWAY1}}
      NETWORK2: {{NETWORK2}}
      NETWORK2_IS_SERVICE: {{NETWORK2_IS_SERVICE}}
      VSPHERE_NETWORK21: {{VSPHERE_NETWORK21}}
      NETWORK2_CIDR1: {{NETWORK2_CIDR1}}
      NETWORK2_RESERVED1: {{NETWORK2_RESERVED1}}
      NETWORK2_DNS1: {{NETWORK2_DNS1}}
      NETWORK2_GATEWAY1: {{NETWORK2_GATEWAY1}}
      VSPHERE_NETWORK22: {{VSPHERE_NETWORK22}}
      NETWORK2_CIDR2: {{NETWORK2_CIDR2}}
      NETWORK2_RESERVED2: {{NETWORK2_RESERVED2}}
      NETWORK2_DNS2: {{NETWORK2_DNS2}}
      NETWORK2_GATEWAY2: {{NETWORK2_GATEWAY2}}
      VSPHERE_NETWORK23: {{VSPHERE_NETWORK23}}
      NETWORK2_CIDR3: {{NETWORK2_CIDR3}}
      NETWORK2_RESERVED3: {{NETWORK2_RESERVED3}}
      NETWORK2_DNS3: {{NETWORK2_DNS3}}
      NETWORK2_GATEWAY3: {{NETWORK2_GATEWAY3}}
      NETWORK3: {{NETWORK3}}
      NETWORK3_IS_SERVICE: {{NETWORK3_IS_SERVICE}}
      VSPHERE_NETWORK31: {{VSPHERE_NETWORK31}}
      NETWORK3_CIDR1: {{NETWORK3_CIDR1}}
      NETWORK3_RESERVED1: {{NETWORK3_RESERVED1}}
      NETWORK3_DNS1: {{NETWORK3_DNS1}}
      NETWORK3_GATEWAY1: {{NETWORK3_GATEWAY1}}
      VSPHERE_NETWORK32: {{VSPHERE_NETWORK32}}
      NETWORK3_CIDR2: {{NETWORK3_CIDR2}}
      NETWORK3_RESERVED2: {{NETWORK3_RESERVED2}}
      NETWORK3_DNS2: {{NETWORK3_DNS2}}
      NETWORK3_GATEWAY2: {{NETWORK3_GATEWAY2}}
      VSPHERE_NETWORK33: {{VSPHERE_NETWORK33}}
      NETWORK3_CIDR3: {{NETWORK3_CIDR3}}
      NETWORK3_RESERVED3: {{NETWORK3_RESERVED3}}
      NETWORK3_DNS3: {{NETWORK3_DNS3}}
      NETWORK3_GATEWAY3: {{NETWORK3_GATEWAY3}}
 
###########################
## Job - Upload ERT      ##
###########################
- name: 4.upload-ert
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-automation
    - get: pcf-products
      params:
        product_slugs:
        - product_slug: elastic-runtime
        product_versions:
        - product_version: {{ERT_VERSION}}
  - task: upload-ert
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/upload-ert.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

# configure ert
- name: 5.configure-ert-vSphere
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: configure-ert
    file:  pcf-automation/pcf-opsman/install-pcf/ci/tasks/configure-ert-vSphere.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AZ_COUNT: {{AZ_COUNT}}
      AZ1: {{AZ1}}
      AZ2: {{AZ2}}
      AZ3: {{AZ3}}
      ERT_SINGLETON_AZ: {{ERT_SINGLETON_AZ}}
      ERT_DOMAIN: {{ERT_DOMAIN}}
      ERT_NETWORK: {{ERT_NETWORK}}
      ERT_SSL_CERT: {{ERT_SSL_CERT}}
      ERT_TEMPLATE: {{ERT_TEMPLATE}}
      HA_PROXY_IPS: {{HA_PROXY_IPS}}
      MYSQL_MONITOR_EMAIL: {{MYSQL_MONITOR_EMAIL}}

# Upload Splunk Tile
- name: 4.3.upload-splunk
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: upload-splunk
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/upload-splunk.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

- name: 5.3.configure-splunk
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: configure-splunk
    file:  pcf-automation/pcf-opsman/install-pcf/ci/tasks/configure-splunk.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AZ_COUNT: {{AZ_COUNT}}
      SPLUNK_TEMPLATE: {{SPLUNK_TEMPLATE}} 
      SPLUNK_JOBS_TEMPLATE: {{SPLUNK_JOBS_TEMPLATE}}
      SPLUNK_NETWORK: {{SPLUNK_NETWORK}}
      ADD_APP_INFO: {{ADD_APP_INFO}}
      CF_API_ENDPOINT: {{CF_API_ENDPOINT}}
      CF_API_USER: {{CF_API_USER}}
      CF_API_PASSWORD: {{CF_API_PASSWORD}}
      FIREHOSE_SUBSCRIPTION_ID: {{FIREHOSE_SUBSCRIPTION_ID}}
      SPLUNK_TOKEN: {{SPLUNK_TOKEN}}
      SPLUNK_INDEX: {{SPLUNK_INDEX}}
      SPLUNK_SERVER: {{SPLUNK_SERVER}}
      SPLUNK_SSL: {{SPLUNK_SSL}}
      SPLUNK_SSL_PASSWORD: {{SPLUNK_SSL_PASSWORD}}
      SPLUNK_SSL_COMMON_NAME: {{SPLUNK_SSL_COMMON_NAME}}
      SPLUNK_SSL_CERT: {{SPLUNK_SSL_CERT}}
      SPLUNK_SSL_ROOT_CA: {{SPLUNK_SSL_ROOT_CA}}
# Upload Datadog Tile
- name: 4.4.upload-datadog
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: upload-datadog
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/upload-datadog.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

- name: 5.4.configure-datadog
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-automation
  - task: configure-datadog
    file:  pcf-automation/pcf-opsman/install-pcf/ci/tasks/configure-datadog.yml
    params: 
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      AZ_COUNT: {{AZ_COUNT}}
      DATADOG_TEMPLATE: {{DATADOG_TEMPLATE}}
      DATADOG_JOBS_TEMPLATE: {{DATADOG_JOBS_TEMPLATE}}
      DATADOG_NETWORK: {{DATADOG_NETWORK}}
      BOSHHMFORWARDER_INCOMING_PORT: {{BOSHHMFORWARDER_INCOMING_PORT}}
      METRON_AGENT_DEPLOYMENT: {{METRON_AGENT_DEPLOYMENT}}
      DOPPLER_USER: {{DOPPLER_USER}}
      DOPPLER_USER_PASSWORD: {{DOPPLER_USER_PASSWORD}}
      INSECURE_SSL_SKIP_VERIFY: {{INSECURE_SSL_SKIP_VERIFY}}
      SUBSCRIPTION_ID: {{SUBSCRIPTION_ID}}
      DATADOG_API_URL: {{DATADOG_API_URL}}
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      METRIC_PREFIX: {{METRIC_PREFIX}}
            
###########################
## Job - Deploy ERT      ##
###########################
- name: 6.apply-changes
  serial: true
  plan:
  - aggregate:
    - get: pcf-automation
  - task: apply-changes
    file: pcf-automation/pcf-opsman/install-pcf/ci/tasks/apply-changes.yml
    params:
      OPSMAN_HOST: {{OPSMAN_HOST}}
      OPSMAN_USER: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}

